scriptPrefixes = {
    'CJK': 'cjk',
    'arabic': 'ar',
    'armenian': 'am',
    'boxdrawings': 'bxd',
    'cyrillic': 'cy',
    'devanagari': 'dv',
    'greek': 'gr',
    'hangul': 'ko',
    'hebrew': 'hb',
    'hiragana': 'hi',
    'ipa': 'ipa',
    'katakana': 'ka',
    'latin': "lt",
    'mongolian' : 'mo',
    'tibetan': 'tb',
}
