# these are names that appear in several scripts and probably need a script prefix
# Names that are reported in the duplicate tests should end up here.

scriptConflictNames = [
    "A",
    "Abreve",
    "Adieresis",
    "E",
    "Edieresis",
    "Gamma",
    "I",
    "Idieresis",
    "Igrave",
    "Imacron",
    "Iota",
    "Koppa",
    "O",
    "Odieresis",
    "Omega",
    "Psi",
    "Schwa",
    "U",
    "Udblacute",
    "Udieresis",
    "Umacron",
    "Upsilon",
    "a", "ae",
    "abreve",
    "adieresis",
    "comma",
    "delta",
    "e",
    "edieresis",
    'gamma',
    "i",
    "idieresis",
    "igrave",
    "imacron",
    'iota',
    "koppa",
    "o", "oe",
    "odieresis",
    "omega",
    "pe",
    'phi',
    "psi",
    "question",
    "u",
    "udblacute",
    "udieresis",
    "umacron",
    'upsilon',
    "yu",
    "ve",

    "numbersign",
    "semicolon",
    'zero', 'one', 'two', 'three', 'four', 'five', 'six',
    'seven', 'eight', 'nine',
    'percent'
]
