import glyphNameFormatter
reload(glyphNameFormatter)
from glyphNameFormatter.unicodeRangeNames import getRangeByName, getAllRangeNames
from glyphNameFormatter.data import unicode2name_AGD

#   Find duplicate names for different unicodes


def findConflict():
    names = {}
    lines = []
    for rangeName in getAllRangeNames():
        start, end = getRangeByName(rangeName)
        for uniNumber in range(start, end+1):
            glyphName = glyphNameFormatter.GlyphName(uniNumber, includeScriptPrefix=False)
            if glyphName.hasName():
                # lines.append("%04X\t%s\t%s" % (uniNumber, glyphName.getName(), glyphName.uniName))
                name = glyphName.getName(extension=False)
                extendedName = glyphName.getName(extension=True)
                if not name in names:
                    names[name] = []
                names[name].append((uniNumber, glyphName.uniRangeName, extendedName))
    n = names.keys()
    n.sort()

    conflictNames = []
    conflictUniNumbers = []
    for name in n:
        if len(names[name]) > 1:
            conflictNames.append(name)
            line = "\n%s" % (name)
            print line
            lines.append(line)
            line = "        %04s%20s%20s%20s%40s"%("hex", "formatted name", "AGL name", "with extension", "range")
            print line
            lines.append(line)
            for g in names[name]:
                conflictUniNumbers.append(g[0])
                AGLname = unicode2name_AGD.get(g[0], "-")
                line = "        %04X%20s%20s%20s%40s"%(g[0], name, AGLname, g[2], g[1])
                print line
                lines.append(line)
    stats =  "# %d names with conflicts, affecting %d unicodes"%(len(conflictNames), len(conflictUniNumbers))
    print stats
    lines.append(stats)


    path = "./../names/conflict.txt"
    f = open(path, 'w')
    f.write("\n".join(lines))
    f.close()


    path = "./../data/scriptConflictNames.py"
    pyText = ["# Table with conflicting names. Generated by /test/testConflicts.py", "\nscriptConflictNames = ["]
    conflictNames.sort()
    for name in conflictNames:
        pyText.append("    \"%s\","%name)
    pyText.append("]\n\n")
    f = open(path, 'w')
    f.write("\n".join(pyText))
    f.close()

if __name__ == "__main__":
    findConflict()
